### ISSUE TITLE
RemoteIP

### ISSUE THREAD

**Issue by eddyyuen** [bbelius/YARP.ReverseProxy.IPFilters#1]
We should try to get RemoteIP from   Header["X-Forwarded-For"]  and then  Header[""X-Real-IP"]  and then RemoteIPAddress

**Comment by bbelius** [comment]
RemoteIPAddress is already being set by YARP, so there is no need for this middleware to parse any forwarded-for headers.
If the reverse proxy is being called form the internet you should also always ignore and delete the forwarded-for headers for security reasons (YARP should take care of that).

**Comment by alefcarlos** [comment]
@bbelius good ? Thats an awesome package!

But I'm have the same doubt, I have the request flow:

`Internet > Azure Application Gateway > Yarp`

My public IP is `189.29.144.200` and that is the value from X-Forwarded-For header.
```
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[9]
      Request and Response:
      Protocol: HTTP/1.1
      Method: GET
      Scheme: http
      PathBase:
      Path: /api-test/todos
      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
      Connection: keep-alive
      Host: apis.qa01.hbsa.com.br
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
      Accept-Encoding: gzip, deflate, br, zstd
      Accept-Language: pt-BR,pt;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
      Cookie: [Redacted]
      Upgrade-Insecure-Requests: [Redacted]
      X-FORWARDED-PROTO: https
      X-FORWARDED-PORT: [Redacted]
      X-Forwarded-For: 189.29.144.200:24691
      X-Original-URL: [Redacted]
      X-AppGW-Trace-Id: [Redacted]
      X-ORIGINAL-HOST: apis.qa01.hbsa.com.br
      sec-ch-ua: [Redacted]
      sec-ch-ua-mobile: [Redacted]
      sec-ch-ua-platform: [Redacted]
      Sec-Fetch-Site: [Redacted]
      Sec-Fetch-Mode: [Redacted]
      Sec-Fetch-User: [Redacted]
      Sec-Fetch-Dest: [Redacted]
      StatusCode: 200
      Content-Type: application/json; charset=utf-8
      Date: Mon, 02 Sep 2024 17:49:44 GMT
      Server: cloudflare
      Access-Control-Allow-Credentials: [Redacted]
      Cache-Control: [Redacted]
      Content-Encoding: [Redacted]
      ETag: [Redacted]
      Expires: -1
      Pragma: [Redacted]
      Vary: [Redacted]
      Via: [Redacted]
      report-to: [Redacted]
      reporting-endpoints: [Redacted]
      nel: [Redacted]
      X-Powered-By: Express
      x-ratelimit-limit: [Redacted]
      x-ratelimit-remaining: [Redacted]
      x-ratelimit-reset: [Redacted]
      X-Content-Type-Options: [Redacted]
      cf-cache-status: [Redacted]
      cf-ray: [Redacted]
      Duration: 372.0232
```

```
IPFilterConfiguration:
  Policies:
    - PolicyName: Teste
      Mode: BlockList
      IPAddresses:
        - 189.29.144.200
```

But the middleware is using my application gateway ip:

```
info: BBelius.Yarp.ReverseProxy.IPFilters.IPFilterPolicyMiddleware[0]
      Request from IP 12.0.6.6 was allowed. Route: api-test. Policy: Teste. Mode: BlockList
```

Is there any way to use the real IP ?

I found this issue https://github.com/microsoft/reverse-proxy/issues/642 to support  UseForwardedHeaders  on Yarp.

**Comment by bbelius** [comment]
@alefcarlos  If possible I would try to configure the Azure Gateway instead of adding another reverse proxy between your application and the gateway. But if you need this setup for some reason:

I would add `app.UseForwardedHeaders(...)` before `app.MapReverseProxy(...)` in the ASP.Net Core pipeline. This way the X-Forwarded-For header will be processed and set in the HttpContext before YARP is even called and it will set the header again for your backend.
Make sure that the Azure Application Gateway is properly setting the X-Forwarded-For header and not accepting this header from internet requests.

```csharp
app.UseRouting();
app.UseCors();    

app.UseForwardedHeaders(...);

app.MapReverseProxy(proxyPipeline =>
{
   proxyPipeline.UseIPFilterPolicies();

   proxyPipeline.UseSessionAffinity();
   proxyPipeline.UseLoadBalancing();
   proxyPipeline.UsePassiveHealthChecks();
});
```

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-8.0#other-proxy-server-and-load-balancer-scenarios

Also, make sure to configure [AllowedHosts](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.forwardedheadersoptions?view=aspnetcore-8.0), so the header is only being processed if it was send from your Azure gateway.

**Comment by alefcarlos** [comment]
Thank you for your response

We are using Azure Gateway as ingress to AKS, so the api gateway is the yarp(here we configure the routing rules, paths e everything else). The ip filter is only a temporary feature until we have WAF implanted. Thats our case. I will try to add the UseForwardedHeaders middleware.

I did not add yet because https://github.com/microsoft/reverse-proxy/issues/642 says the yarp may have trouble using it.

**Comment by bbelius** [comment]
@alefcarlos  You could also implement a middleware that reads the necassary headers before YARP is being called, store them in HttpContext.Items and process them in a fork of the IPFilter middleware. This way you would be able to block requests, but all apps downstream would still only get the Azure Gateway IP address and Host. This will mess up your logs and metrics, so I would try UseForwardedHeaders first before going down that route.
